apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-list-pv
spec:
  capacity:
    storage: 1Gi   
  accessModes:
    - ReadWriteOnce  
  hostPath:
    path: /mnt/data/todo-list   
  persistentVolumeReclaimPolicy: Retain  
